<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2020 Red Hat, Inc. and/or its affiliates
    and other contributors as indicated by the @author tags.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jboss</groupId>
        <artifactId>jboss-parent</artifactId>
        <version>49</version>
    </parent>
    <groupId>org.wildfly.galleon.feature-packs</groupId>
    <artifactId>wildfly-galleon-feature-packs-parent</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <name>WildFly Galleon feature-packs parent</name>
    <description>WildFly Galleon feature-packs parent</description>
    <url>https://github.com/wildfly/wildfly-galleon-feature-packs</url>
    <licenses>
      <license>
        <name>Apache License 2.0</name>
        <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
        <distribution>repo</distribution>
      </license>
    </licenses>
    <developers>
      <developer>
        <id>jdenise</id>
        <name>Jean-Francois Denise</name>
        <organization>Red Hat</organization>
      </developer>
    </developers>
    <properties>
        <version.org.wildfly.glow>2.0.0.Beta1</version.org.wildfly.glow>
        <version.gpg.plugin>3.2.8</version.gpg.plugin>
        <version.nxrm3.plugin>1.0.7</version.nxrm3.plugin>
        <!-- maven-gpg-plugin -->
        <!-- set this to "error" to require a GPG agent-->
        <gpg.pinEntryMode>loopback</gpg.pinEntryMode>
        <!-- Nexus deployment settings -->
        <nexus.serverId>jboss</nexus.serverId>
        <nexus.repo.name>wildfly-staging</nexus.repo.name>
        <nexus.repo.url>https://repository.jboss.org/nexus</nexus.repo.url>
        <nexus.destination.repo.name>releases</nexus.destination.repo.name>
        <nexus.staging.tag>wildfly-galleon-feature-packs-${project.version}</nexus.staging.tag>
        <wildfly.repo.scm.connection>git@github.com:wildfly/wildfly-galleon-feature-packs.git</wildfly.repo.scm.connection>
        <wildfly.repo.scm.url>https://github.com/wildfly/wildfly-galleon-feature-packs</wildfly.repo.scm.url>
    </properties>
    <scm>
      <connection>scm:git:${wildfly.repo.scm.connection}</connection>
      <developerConnection>scm:git:${wildfly.repo.scm.connection}</developerConnection>
      <url>${wildfly.repo.scm.url}</url>
      <tag>HEAD</tag>
    </scm>
    <build>
      <pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nxrm3-maven-plugin</artifactId>
            <version>${version.nxrm3.plugin}</version>
            <configuration>
              <serverId>${nexus.serverId}</serverId>
              <nexusUrl>${nexus.repo.url}</nexusUrl>
              <repository>${nexus.repo.name}</repository>
            </configuration>
          </plugin>
        </plugins>
      </pluginManagement>
    </build>
    <profiles>
      <!-- Temporarily override the jboss-parent jboss-release profile
      to add configuration related to Nexus 3 deployment. These
      are expected to come in a later jboss-parent release -->
      <!-- TODO remove this content when it is included in jboss-parent -->
      <profile>
        <id>jboss-release</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-deploy-plugin</artifactId>
              <executions>
                <execution>
                  <id>default-deploy</id>
                  <phase>none</phase>
                </execution>
              </executions>
            </plugin>
            <plugin>
              <groupId>org.sonatype.plugins</groupId>
              <artifactId>nxrm3-maven-plugin</artifactId>
              <extensions>true</extensions>
              <executions>
                <execution>
                  <id>nexus-deploy</id>
                  <phase>deploy</phase>
                  <goals>
                    <goal>deploy</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-gpg-plugin</artifactId>
              <configuration>
                <useAgent>true</useAgent>
                <gpgArguments>
                  <arg>--pinentry-mode</arg>
                  <arg>${gpg.pinEntryMode}</arg>
                </gpgArguments>
              </configuration>
              <executions>
                <execution>
                  <id>gpg-sign</id>
                  <goals>
                    <goal>sign</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </build>
      </profile>
      <!-- Use this profile in combination with 'jboss-release' to use
      the nxrm3-maven-plugin's 'staging-deploy' goal instead of its
      'deploy' goal. Once the staged deployment is valdated, the
      person or script doing the release  would move on to use
      its 'staging-move' goal via a call to
      'mvn nxrm3:staging-move -Pjboss-staging-move' -->
      <!-- TODO remove this content when it is included in jboss-parent -->
      <profile>
        <id>jboss-staging-deploy</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.sonatype.plugins</groupId>
              <artifactId>nxrm3-maven-plugin</artifactId>
              <executions>
                <!-- Disable the jboss-release profile's 'deploy' goal execution -->
                <execution>
                  <id>nexus-deploy</id>
                  <phase>none</phase>
                </execution>
                <execution>
                  <id>nexus-staging.deploy</id>
                  <phase>deploy</phase>
                  <goals>
                    <goal>staging-deploy</goal>
                  </goals>
                  <configuration>
                    <tag>${nexus.staging.tag}</tag>
                  </configuration>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </build>
      </profile>
      <!-- Used in release workflows that use the 'jboss-staging-deploy' profile,
      this profile configures the nxrm3-maven-plugin to support command
      line execution of its 'staging-move' goal. -->
      <!-- TODO remove this content when it is included in jboss-parent -->
      <profile>
        <id>jboss-staging-move</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.sonatype.plugins</groupId>
              <artifactId>nxrm3-maven-plugin</artifactId>
              <configuration>
                <destinationRepository>${nexus.destination.repo.name}</destinationRepository>
                <tag>${nexus.staging.tag}</tag>
              </configuration>
            </plugin>
          </plugins>
        </build>
      </profile>
      <!-- Used in release workflows that use the 'jboss-staging-deploy' profile,
      this profile configures the nxrm3-maven-plugin to support command
      line execution of its 'staging-delete' goal. -->
      <!-- TODO remove this content when it is included in jboss-parent -->
      <profile>
        <id>jboss-staging-delete</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.sonatype.plugins</groupId>
              <artifactId>nxrm3-maven-plugin</artifactId>
              <configuration>
                <tag>${nexus.staging.tag}</tag>
              </configuration>
            </plugin>
          </plugins>
        </build>
      </profile>
    </profiles>
</project>
