<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2020 Red Hat, Inc. and/or its affiliates
    and other contributors as indicated by the @author tags.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.wildfly.galleon.feature-packs</groupId>
        <artifactId>wildfly-galleon-feature-packs-parent</artifactId>
        <version>1.0</version>
    </parent>
    <groupId>org.wildfly.galleon.feature-packs</groupId>
    <artifactId>wildfly-galleon-feature-packs-metadata</artifactId>
    <version>23.0</version>
    <packaging>pom</packaging>

    <name>WildFly Galleon feature-packs maven metadata</name>
    <description>WildFly Galleon feature-packs maven metadata</description>
    <url>https://github.com/wildfly/wildfly-galleon-feature-packs</url>
    <licenses>
      <license>
        <name>Apache License 2.0</name>
        <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
        <distribution>repo</distribution>
      </license>
    </licenses>
    <developers>
      <developer>
        <id>jdenise</id>
        <name>Jean-Francois Denise</name>
        <organization>Red Hat</organization>
      </developer>
    </developers>
    <scm>
      <connection>scm:git:${wildfly.repo.scm.connection}</connection>
      <developerConnection>scm:git:${wildfly.repo.scm.connection}</developerConnection>
      <url>${wildfly.repo.scm.url}</url>
      <tag>HEAD</tag>
    </scm>
    <build>
        <plugins>
            <plugin>
                <groupId>org.wildfly.glow</groupId>
                <artifactId>wildfly-glow-doc-plugin</artifactId>
                <version>${version.org.wildfly.glow}</version>
                <configuration>
                    <targetDir>${basedir}/target</targetDir>
                    <repoPath>${basedir}/../..</repoPath>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-maven-metadata</id>
                        <goals>
                            <goal>generate-maven-metadata</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
